#!/bin/sh
ipset -N china hash:net
for i in $(cat /opt/lnmp-debian/ipset/cn.zone ); do ipset -A china $i; done
ipset -N blacklist hash:net
for i in $(cat /opt/lnmp-debian/ipset/ipset-blacklist.txt ); do ipset -A blacklist $i; done
/sbin/iptables-restore < /opt/lnmp-debian/iptables.up.rules
